### ISSUE TITLE
通过steedos-config 配置文件设置accounts 生成的token 的属性

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-accounts#19]
```
accounts: 
  tokenSecret: 'secret'
  accessTokenExpiresIn: 365d
  refreshTokenExpiresIn: 7d
```
